# Change these first
owner: greenbotlabs # Your GitHub organization or username, where this repository lives
repo: odm_server_status # The name of this repository

sites:
  - name: Mosaicos (CHI)
    url: https://mosaicos.bosquedigital.cl
  - name: DRONE (CONST)
    url: https://drone.bosquedigital.cl
  - name: SGM (ARAU)
    url: https://sgm.bosquedigital.cl
  - name: SGM-VALDIVIA (VALD)
    url: https://sgm-valdivia.bosquedigital.cl
  - name: CLUSTER
    url: http://cluster.bosquedigital.cl
    port: 10000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SERVERS ODM
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /odm_server_status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
